version: '2'
services:
  php7:
    image: blind_php7
    container_name: blind_php7
    links:
      - mysql
    ports:
      - 80:80
    volumes_from:
      - app

  app:
    env_file:
      - .env
    image: blind_symfony
    container_name: blind_symfony
    volumes:
      - "${SYMFONY}:/var/www/html/"
    tty: true

  mysql:
    env_file:
      - .env
    image: blind_mysql
    container_name: blind_mysql
    volumes:
      - "${DBHOST}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${PASSROOT}"
      MYSQL_DATABASE: "${NAMEDB}"
      MYSQL_USER: "${USERDB}"
      MYSQL_PASSWORD: "${PASSDB}"
    ports:
      - 3306:3306