version: '3'
services:
  php7:
    image: blind_php
    container_name: blind_php
    expose:
      - 9000:9000
    volumes_from:
      - app
    links:
      - mysql

  apache:
    image: blind_apache
    container_name: blind_apache
    links:
      - php7
    ports:
      - 80:80
    volumes_from:
      - app

  app:
    image: blind_app
    container_name: blind_app
    volumes:
      - /var/www/symfony
    tty: true

  myadmin:
    image: blind_myadmin
    container_name: blind_myadmin
    links:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - /var/www/html

  mysql:
    image: blind_mysql
    container_name: blind_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password