version: '2'
services:
  php7:
    image: blind_php7
    container_name: blind_php7
    ports:
      - 9000:9000
    volumes_from:
      - app
    links:
      - mysql

  apache:
    image: blind_apache
    container_name: blind_apache
    links:
      - php7
    ports:
      - 80:80
    volumes_from:
      - app

  app:
    image: blind_symfony
    container_name: blind_symfony
    volumes:
      - /home/pi/Symfony:/var/www/html/web/Symfony
    tty: true

  mysql:
    image: blind_mysql
    container_name: blind_mysql
    volumes:
      - /home/pi/Data:/var/lib/mysql
    ports:
      - 3306:3306